### ISSUE TITLE
Add custom class for tracking selection pills

### ISSUE THREAD

**Issue by jkrenge** [parcelLab/parcelLab-js-plugin#11]
If we do have multiple tracking numbers and select via `?u=1&orderNo=`, can we add a custom class depending on the current status of the tracking?

So they could highlight the pills in red if there's an exception with their own CSS, for example.

**Comment by andruschka** [comment]
done, tab will get pl-tab-{{transitStatus}}
e.g.: pl-tab-pickupreadynextday
