### ISSUE TITLE
Tested with Firefox v24?

### ISSUE THREAD

**Issue by jkrenge** [parcelLab/parcelLab-js-plugin#14]
There might be issues with older version of Firefox

We should also include a no-javascript-notice in our HTML code

**Comment by andruschka** [comment]
Firefox 24 :D wo soll ich das herkriegen 
aktuell ist 64 oder so 😂
ja son no-js banner macht sinn evtl

**Comment by jkrenge** [comment]
Okay, wusste nicht dass das 10 Jahre alt ist :D

Aber no-js auf jeden Fall, das können wir ja einfach in die Docs schreiben?

**Comment by sehecker** [comment]
won't do
