### ISSUE TITLE
🇭🇺Hungarian Tracking Page

### ISSUE THREAD

**Issue by sehecker** [parcelLab/parcelLab-js-plugin#19]
[Hungarian translation](https://app.zenhub.com/files/107708348/80fa0f0c-586a-4c2f-9397-9614e10cfc98/download)

**Comment by andruschka** [comment]
Tracking page and versand-status.de lang switcher now hast HU as lang.
Checkpoints translations are not ready?!
@jkrenge @sehecker 
https://www.versand-status.de/?borderRadius=0px&borderColor=dddddd&u=1612164&orderNo=8001978865&language=de&disableVoting=yes&rerouteButton=left&s=5965d6a0&lang=hu&

**Comment by andruschka** [comment]
@jkrenge pushed statusCodes to master. Dont know hot to deploy this tho'...

**Comment by jkrenge** [comment]
thx 🙏

It's a normal API deploy, the CSV is parsed
