### ISSUE TITLE
update instagram integration

### ISSUE THREAD

**Issue by arsylum** [parcelLab/parcelLab-js-plugin#20]
new api response format

**Comment by arsylum** [comment]
https://github.com/parcelLab/parcelLab-js-plugin/pull/21
assuming that the js plugin should only render 1 (the most recent) post, that is all there is to it

**Comment by gasserdav28** [comment]
also das ist mal die erste seite die ich entworfen habe. Würde gerne noch einen header/title oben drüber machen. Ideen?

<img width="1552" alt="Screenshot 2019-08-19 at 14 44 18" src="https://user-images.githubusercontent.com/43746331/63266321-ff3fe480-c28f-11e9-8d3d-670e66e0ed61.png">
