### ISSUE TITLE
Code snippet to inject custom text into split-order pills

### ISSUE THREAD

**Issue by jkrenge** [parcelLab/parcelLab-js-plugin#25]
Currently the selection for split-orders looks like this:

![Screenshot 2019-04-12 at 11.28.58.png](https://images.zenhubusercontent.com/5a073c418a75884b9087047b/abf30779-dc69-4f0e-8fd6-1a495e191aec)

Now we want customers to be able to modify these buttons individually using the `onnRendered` hook.

Can we provide a JS function to be inserted there that inject additional titles based on the carrier so that it looks like this?

![Screenshot 2019-04-12 at 11.31.40.png](https://images.zenhubusercontent.com/5a073c418a75884b9087047b/4585430f-0e2f-4d70-973c-6a568fb6862d)

**Comment by sehecker** [comment]
@jkrenge what is more urgent, this here or #680 ? We cannot do both this week

**Comment by jkrenge** [comment]
Less urgent than parcelLab/Backend#680 but actually this can be done by anyone, doesn't need to be Andrej :-) I think @kontry  would like it

**Comment by jkrenge** [comment]
Das wird kein allgemeines Feature, sondern nur ein Hook, den die einmalig und nur bei sich im Shop einbinden

**Comment by sehecker** [comment]
How about inject something like "Status Ihrer Retoure" instead of "Status Ihrer Sendung" etc. for return trackings?

**Comment by andruschka** [comment]
@kontry here some help - just as a tip how to insert text elements with JS...

document.querySelectorAll('.pl-tab-text').forEach(el => {
  var newElem = document.createElement('span')
  newElem.classList.add('pl-tab-text-status')
  newElem.style.display = 'block'
  newElem.innerText = 'HIER DER TEXT'
  el.insertBefore(newElem, el.children[0])
})

**Comment by jkrenge** [comment]
Doing this week?

**Comment by kontry** [comment]
We'll try! 💪

**Comment by kontry** [comment]
```
        onRendered: function(state) {
          console.log('rerendered!', state);
          if (state.checkpoints && state.checkpoints.header.length > 1) {
            document.querySelectorAll('.pl-tab-text').forEach(function(el, index) {
              var newElem = document.createElement('span');
              newElem.classList.add('pl-tab-text-status');
              newElem.style.display = 'block';
              if (state.checkpoints.header[index].courier.name === 'dhl-germany' && el.querySelectorAll('.pl-tab-text-status').length <= 1) {
                newElem.innerText = 'Paketlieferung';
                el.insertBefore(newElem, el.children[0]);
              } else if (state.checkpoints.header[index].courier.name === 'rhenus-home-delivery' && el.querySelectorAll('.pl-tab-text-status').length <= 1) {
                newElem.innerText = 'Speditionslieferung';
                el.insertBefore(newElem, el.children[0]);
              } else if (state.checkpoints.header[index].courier.name === 'sedilog' && el.querySelectorAll('.pl-tab-text-status').length <= 1) {
                newElem.innerText = 'Speditionslieferung';
                el.insertBefore(newElem, el.children[0]);
              }
            });
          }
        }
```

**Comment by kontry** [comment]
![Screenshot 2019-05-17 at 18.11.18.png](https://images.zenhubusercontent.com/5c7e43e456a66a2b0714cfb9/9f7667a9-9bd8-4507-bd20-37fcce8fbb11)

**Comment by jkrenge** [comment]
Von mir aus Close, Info ist raus --> Code noch nach StackOverflow

**Comment by kontry** [comment]
Ist jetzt auf StackOverflow :)

https://stackoverflow.com/c/parcellab/questions/110
