### ISSUE TITLE
Add Slovakian 🇸🇰, Slovenian 🇸🇮 and Czech 🇨🇿 to tracking page

### ISSUE THREAD

**Issue by jkrenge** [parcelLab/parcelLab-js-plugin#27]

**Comment by sehecker** [comment]
[SK & CZ Texte](https://app.zenhub.com/files/64418699/73b1badb-8693-45da-a8f1-d7e640734aa9/download)

**Comment by jkrenge** [comment]
Ist das überprüft ob alle Texte drin sind?

**Comment by andruschka** [comment]
Ich glaube Slovenian 1 Dokument ist nicht vollständig oder wird mir das nur so angezeigt? 
Schau mal rein @sehecker

**Comment by andruschka** [comment]
- [ ] JS plugin
  - [ ] CS
  - [ ] SK
  - [ ] SL

- [ ] Matchings
  - [ ] CS
  - [ ] SK
  - [ ] SL

**Comment by sehecker** [comment]
Das müssen wir diese Woche jetzt fertig bekommen. Klingel wartet darauf.

**Comment by SunnyBrenner** [comment]
@andruschka wie weit bist du?
Das soll Ende der Woche live gehen.

**Comment by SunnyBrenner** [comment]
@jkrenge sagst du bescheid, wenn das live ist? :)

**Comment by sehecker** [comment]
Das ist schon live, weil in `closed`

**Comment by SunnyBrenner** [comment]
ah perfekt!
