### ISSUE TITLE
bricozor [user_id :1614052] - sorting of checkpoints on the track&trace is off

### ISSUE THREAD

**Issue by dominikmeyerPL** [parcelLab/parcelLab-js-plugin#45]
We get the files containing the bricozor trackings late. Thus, there are checkpoints from the carrier that have an earlier timestamp.
That and some strange sorting error cause the a non-chronological display of checkpoints on the track and trace page. Since the "Order processed" box will almost always have a later timestamp than the pickup scheduled one we could additionally hide the date of this checkpoint to make it less confusing for the recipient of the parcel.

https://prtl.parcellab.com/trackings/details?trackingNo=9L25708785561&courier=colissimo

![image.png](https://images.zenhubusercontent.com/5dc94e610f20bf0001e1aa8e/fb7edb96-8bf6-480a-be94-a6cd5f9e054d)

![image.png](https://images.zenhubusercontent.com/5dc94e610f20bf0001e1aa8e/b5d67049-e815-4f35-8044-bd81b4da8a56)

**Comment by andruschka** [comment]
@dominikmeyerPL should be done ;-)
