### ISSUE TITLE
Search form doesn't show results

### ISSUE THREAD

**Issue by jkrenge** [parcelLab/parcelLab-js-plugin#7]
Allerdings wollten wir jetzt das Suchformular integrieren, wenn die Seite im Shop ohne Sendungsnummer aufgerufen wird. Dazu habe ich wie in der Doku beschrieben die Initialisierung mit den entsprechenden Parametern aufgerufen:

`parcelLab.initialize({   show_searchForm: true,   userId: 1, });`

Allerdings ist die Ausgabe auf der Seite die gleiche, wie bei einer Initialisierung ohne die entsprechenden Parameter.

Ich sehe im Code auch, dass eigentlich ein Fehler geworfen werden sollte, wenn man keine userId angibt:

`console.error("⚠️  You must pass your userId in the options if you want to display a searchForm!")`

Das habe ich auch einmal probiert (keine userId angegeben) und keine Fehlermeldung in der Konsole sehen können. Übersehe ich da irgendetwas? Die Anzeige der Test-Tracking-Nummern, die du uns gegeben hast funktioniert soweit ohne Probleme.

**Comment by andruschka** [comment]
Does the client use the right method for init opts ? because its like that: 
`      var pl = new ParcelLab('#app-root', { styles: true, rerouteButton: 'left' })
      pl.initialize()
`

**Comment by andruschka** [comment]
pl.initialize() does not get any opts ...

**Comment by jkrenge** [comment]
I think this worked, waiting for their feedback.

**Comment by jkrenge** [comment]
All good.
