### ISSUE TITLE
Documentation down

### ISSUE THREAD

**Issue by GuillaumeAmat** [parcelLab/parcelLab-js-plugin#75]
Hello,

The documentation link (displayed on that repo's home) is down: https://docs.parcellab.com/retrieve/#javascript_libraries

Is there another documentation deployed somewhere?

**Comment by lacazeto** [comment]
That link referred to the old public docs parcelLab had at the time, which has now been replaced by `https://how.parcellab.works/docs/`.

I just checked the web archive and that was what we had 4 years ago (https://web.archive.org/web/20180925112710/https://docs.parcellab.com/)

And in 2019 the old one was already being redirected to the new docs page (https://web.archive.org/web/20190718191411/https://docs.parcellab.com/).

So please refer to this link for the official public documentation (https://how.parcellab.works/docs/integration-quick-start/track-and-trace-page). I'll update the repo's info!
